pipeline:
  build:
    image: golang:1.8
    commands:
      - go get github.com/mattn/goveralls
      - $HOME/gopath/bin/goveralls -service=travis-ci

services:
  postgres:
    image: postgres:9.4.5
    environment:
      - POSTGRES_USER=myapp