pipeline:
  build:
    image: golang:1.8
    commands:
      - export GOPATH=/drone
      - export PATH=$PATH:$GOPATH/bin
      - go get github.com/micro/go-micro
      - go get gopkg.in/yaml.v2
      - go get github.com/mattn/goveralls
      - goveralls -service=drone.io
