language: go
sudo: false
go:
  - 1.9
before_install:
  - get -t ./...
script:
  - echo "do something here maybe"
before_deploy:
  - export GIT_TAG=$(cat VERSION)
deploy:
  provider: script
  script: echo ${GIT_TAG}
  on:
    branch: master