language: go
sudo: false
go:
  - 1.9
before_install:
  - echo "would do go get -t ./..."
script:
  - echo "do something here maybe"
before_deploy:
  - export GIT_TAG=$(cat VERSION)
  - echo ${GIT_TAG}
